name: umpire-quiz

services:
  #  reverse-proxy:
  #    image: bramjanssens/umpire-quiz-reverse-proxy:${PROXY_VERSION}
  #    ports:
  #      - "81:80"

  frontend:
    build: .
    ports:
      - "8080:80"
    environment:
      QUESTION_SERVICE_URL: "http://localhost:9080/question"
      IMPORTER_URL: "http://localhost:9081/importer"
      USER_SERVICE_URL: "http://localhost:9083/user"
